create TABLE DEPARTMENT_VIEW_TIME_RANGE(
ID NUMBER PRIMARY KEY ,
DEPARTMENT_ID NUMBER,
DEPARTMENT_NAME VARCHAR2(50),
START_TIME DATE,
END_TIME DATE,
MEMBER_ID NUMBER,
DAY_NUM NUMBER
);

-- 离职设置
create table leave_config(
id number primary key ,
is_enable CHAR DEFAULT 0
);