create TABLE DEPARTMENT_VIEW_TIME_RANGE(
ID NUMBER PRIMARY KEY ,
DEPARTMENT_ID NUMBER,
DEPARTMENT_NAME VARCHAR2(50),
START_TIME DATE,
END_TIME DATE,
MEMBER_ID NUMBER,
DAY_NUM NUMBER
);

-- 禁用模板流程
CREATE TABLE TEMP_TEMPLATE_STOP(
    ID NUMBER NOT NULL primary key,
    TEMPLATE_ID VARCHAR2(100),
    ORG_ACCOUNT_ID VARCHAR2(100),
    P2 VARCHAR2(255),
    P3 VARCHAR2(255),
    P1 VARCHAR2(255)
)