package com.seeyon.apps.govdoc.po;

import java.io.Serializable;

// default package
// Generated 2015-11-13 16:41:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import com.seeyon.v3x.common.domain.BaseModel;

/**
 * 公文交换记录
 * GovdocExchangeDetail generated by hbm2java
 */
public class GovdocExchangeDetail extends BaseModel implements Serializable {

	private static final long serialVersionUID = 1758494310412973900L;
	
	private Long mainId;
	private Long sendAccountId;
	private Long recOrgId;//接收单位id
	private Long recAccountId;//接收单位id或者部门id  优先为部门id 
	private int recOrgType;
	private String recOrgName;
	private String content;
	private String recNo;
	private String recUserName;
	private Long recUserId;
	private Date recTime;
	//交换状态  参考 com.seeyon.apps.govdoc.util.GovDocEnum.ExchangeDetailStatus
	private int status;
	private int cuibanNum;
	//签收流程的公文id
	private Long summaryId;
	private Long nodeInfo;
	// 收文流程id
	private Long recSummaryId;
	private String opinion;
	private Date createTime;
	@SuppressWarnings("rawtypes")
	private Map attrMap;//扩展属性
	//签收或者分办的时候
	private Long signAffairId;
	private String extAttr;
	private String sendUnit;//交换单位,查询的时候使用,对应的值是来文的拟稿单位


	public GovdocExchangeDetail() {}

	public GovdocExchangeDetail(Long mainId, Long recOrgId, int recOrgType, int status) {
		this.mainId = mainId;
		this.recOrgId = recOrgId;
		this.recOrgType = recOrgType;
		this.status = status;
	}
	public GovdocExchangeDetail(Long mainId, Long recOrgId,
			int recOrgType, String recOrgName, String recNo, String recUserName, Date recTime,
			int status, int cuibanNum) {
		this.mainId = mainId;
		this.recOrgId = recOrgId;
		this.recOrgType = recOrgType;
		this.recOrgName = recOrgName;
		this.recNo = recNo;
		this.recUserName = recUserName;
		this.recTime = recTime;
		this.status = status;
		this.cuibanNum = cuibanNum;
	}
	
	public String getExtAttr() {
		return extAttr;
	}
	public void setExtAttr(String extAttr) {
		this.extAttr = extAttr;
	}
	public Long getSignAffairId() {
		return signAffairId;
	}
	public void setSignAffairId(Long signAffairId) {
		this.signAffairId = signAffairId;
	}
	@SuppressWarnings("rawtypes")
	public Map getAttrMap() {
		if(attrMap==null){
			attrMap = new HashMap();
		}
		return attrMap;
	}
	@SuppressWarnings("rawtypes")
	public void setAttrMap(Map attrMap) {
		this.attrMap = attrMap;
	}
	public Long getSendAccountId() {
		return sendAccountId;
	}
	public void setSendAccountId(Long sendAccountId) {
		this.sendAccountId = sendAccountId;
	}
	public Long getSummaryId() {
		return summaryId;
	}
	public void setSummaryId(Long summaryId) {
		this.summaryId = summaryId;
	}
	public Long getMainId() {
		return this.mainId;
	}
	public void setMainId(Long mainId) {
		this.mainId = mainId;
	}
	public int getRecOrgType() {
		return this.recOrgType;
	}
	public void setRecOrgType(int recOrgType) {
		this.recOrgType = recOrgType;
	}
	public String getRecOrgName() {
		return this.recOrgName;
	}
	public void setRecOrgName(String recOrgName) {
		this.recOrgName = recOrgName;
	}
	public String getRecNo() {
		return this.recNo;
	}
	public void setRecNo(String recNo) {
		this.recNo = recNo;
	}
	public String getRecUserName() {
		return this.recUserName;
	}
	public void setRecUserName(String recUserName) {
		this.recUserName = recUserName;
	}
	public Date getRecTime() {
		return this.recTime;
	}
	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}
	public int getStatus() {
		return this.status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public int getCuibanNum() {
		return this.cuibanNum;
	}
	public void setCuibanNum(int cuibanNum) {
		this.cuibanNum = cuibanNum;
	}
	public Long getRecSummaryId() {
		return recSummaryId;
	}
	public void setRecSummaryId(Long recSummaryId) {
		this.recSummaryId = recSummaryId;
	}
	public String getOpinion() {
		return opinion;
	}
	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Long getRecOrgId() {
		return recOrgId;
	}
	public void setRecOrgId(Long recOrgId) {
		this.recOrgId = recOrgId;
	}
	public Long getNodeInfo() {
		return nodeInfo;
	}
	public void setNodeInfo(Long nodeInfo) {
		this.nodeInfo = nodeInfo;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public Long getRecUserId() {
		return recUserId;
	}
	public void setRecUserId(Long recUserId) {
		this.recUserId = recUserId;
	}	
	public String getSendUnit() {
		return sendUnit;
	}
	public void setSendUnit(String sendUnit) {
		this.sendUnit = sendUnit;
	}
	public Long getRecAccountId() {
		return recAccountId;
	}
	public void setRecAccountId(Long recAccountId) {
		this.recAccountId = recAccountId;
	}	
}
