package com.seeyon.apps.govdoc.po;

import java.io.Serializable;

// default package
// Generated 2015-11-13 16:41:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;

import com.seeyon.v3x.common.domain.BaseModel;

/**
 * 公文交换主表
 * GovdocExchangeMain generated by hbm2java
 */
public class GovdocExchangeMain extends BaseModel implements Serializable {
	
	private static final long serialVersionUID = -2935184499088053982L;
	
	public final static int EXCHANGE_TYPE_JIAOHUAN = 0;//默认交换
	public final static int EXCHANGE_TYPE_LIANHE = 1;//联合发文
	public final static int EXCHANGE_TYPE_ZHUANSHOUWEN = 2;//转收文
	public final static int EXCHANGE_TYPE_ZHUANFAWEN = 3;//转发文
	
	private String subject;
	private Date createTime;
	private Long startUserId;
	private Date startTime;
	private String createPerson;
	private Long summaryId;
	private Long affairId;
	private String ocipSysCode;
	private int type = EXCHANGE_TYPE_JIAOHUAN;
	/**
	 * 主公文id，目前适用于转发文
	 * summaryId-被关联的公文id
	 */
	private Long referenceId;
	
	/**
	 * 用于收文查看所有转发文列表时公文文号，仅做展示
	 */
	private String docMark;
	/**
	 * 交换之前的原始文件id
	 */
	private Long originalFileId;
	
	public GovdocExchangeMain() {
	}

	public String getOcipSysCode() {
		return ocipSysCode;
	}
	public void setOcipSysCode(String ocipSysCode) {
		this.ocipSysCode = ocipSysCode;
	}
	public Long getSummaryId() {
		return summaryId;
	}
	public void setSummaryId(Long summaryId) {
		this.summaryId = summaryId;
	}
	public Long getAffairId() {
		return affairId;
	}
	public void setAffairId(Long affairId) {
		this.affairId = affairId;
	}	
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Long getStartUserId() {
		return startUserId;
	}
	public void setStartUserId(Long startUserId) {
		this.startUserId = startUserId;
	}
	public Date getStartTime() {
		return startTime;
	}
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	public String getCreatePerson() {
		return createPerson;
	}
	public void setCreatePerson(String createPerson) {
		this.createPerson = createPerson;
	}
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public Long getReferenceId() {
		return referenceId;
	}
	public void setReferenceId(Long referenceId) {
		this.referenceId = referenceId;
	}
	@Column(name = "docMark")
	public String getDocMark() {
		return docMark;
	}
	public void setDocMark(String docMark) {
		this.docMark = docMark;
	}

	public Long getOriginalFileId() {
		return originalFileId;
	}

	public void setOriginalFileId(Long originalFileId) {
		this.originalFileId = originalFileId;
	}
	
	
}
