package com.seeyon.apps.govdoc.po;

import java.io.Serializable;
import java.util.Date;

import com.seeyon.v3x.common.domain.BaseModel;

/**
 * 公文交换记录日志
 * GovdocExchangeDetailLog generated by hbm2java
 */
public class GovdocExchangeDetailLog extends BaseModel implements Serializable {

	private static final long serialVersionUID = 858413563288270050L;
	
	private long detailId;
	private String userName;
	private Date time;
	private String description;
	private int status;
	private int cuibanNum;
	private String backOpinion;
	private Long backSummaryId; 
	//毫秒数
	private Integer timeMS;

	public GovdocExchangeDetailLog() {
	}
	public GovdocExchangeDetailLog(long detailId, int status) {
		this.detailId = detailId;
		this.status = status;
	}
	public GovdocExchangeDetailLog(long detailId, String userName,
			Date time, int status, int cuibanNum) {
		this.detailId = detailId;
		this.userName = userName;
		this.time = time;
		this.status = status;
		this.cuibanNum = cuibanNum;
	}
	public GovdocExchangeDetailLog clone() {
		try {
			return (GovdocExchangeDetailLog) super.clone();
		} catch(CloneNotSupportedException e) {
			return null;
		}
	}
	
	public Integer getTimeMS() {
		return timeMS;
	}
	public void setTimeMS(Integer timeMS) {
		this.timeMS = timeMS;
	}
	public Long getBackSummaryId() {
		return backSummaryId;
	}
	public void setBackSummaryId(Long backSummaryId) {
		this.backSummaryId = backSummaryId;
	}
	public String getBackOpinion() {
		return backOpinion;
	}
	public void setBackOpinion(String backOpinion) {
		this.backOpinion = backOpinion;
	}
	public long getDetailId() {
		return this.detailId;
	}
	public void setDetailId(long detailId) {
		this.detailId = detailId;
	}
	public String getUserName() {
		return this.userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public Date getTime() {
		return this.time;
	}
	public void setTime(Date time) {
		this.time = time;
	}
	public int getStatus() {
		return this.status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public int getCuibanNum() {
		return this.cuibanNum;
	}
	public void setCuibanNum(int cuibanNum) {
		this.cuibanNum = cuibanNum;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
}
