




CREATE TABLE "MID_POST" (
"ID" NUMBER(18) NOT NULL PRIMARY KEY,
"POST_CODE" VARCHAR2(255 BYTE) NULL ,
"POST_NAME" VARCHAR2(255 BYTE) NULL ,
"POST_DESC" VARCHAR2(255 BYTE) NULL ,
"ACCOUNT_ID" NUMBER(18) NULL ,
"OPERATION_TYPE" NUMBER(18) NULL ,
"SORT_ID" NUMBER(18) NULL ,
"OA_TYPE" NUMBER(18) NULL ,
"POST_ID" NUMBER NULL
)
