package com.seeyon.v3x.edoc.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * EdocMarkDefinition generated by MyEclipse - Hibernate Tools
 */
public class EdocMarkDefinition extends BaseModel implements Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3536716036103840607L;
	//Fields 
	private Long categoryId;
    private String wordNo;
//    private boolean yearEnabled;
    private String expression;
    private Integer length;
    private Short status;
    private Long domainId;     
    //文号类型，内部文号||公文文号
    private Integer markType;
    //G6 V1.0 SP1后续功能_自定义签收编号
    private String selectV;//下拉框赋值
    
    private Integer sortNo;
    
    private EdocMarkCategory edocMarkCategory;
    private List<EdocMarkAcl> markAclList = new ArrayList<EdocMarkAcl>();
    
    public String getSelectV() {
		return selectV;
	}

	public void setSelectV(String selectV) {
		this.selectV = selectV;
	}

	private Set<EdocMarkAcl> edocMarkAcls = new HashSet<EdocMarkAcl>(0);

    // Constructors

    /** default constructor */
    public EdocMarkDefinition() {
    }
	
    // Property accessors
  
    public EdocMarkCategory getEdocMarkCategory() {
        return this.edocMarkCategory;
    }
    
    public void setEdocMarkCategory(EdocMarkCategory edocMarkCategory) {
        this.edocMarkCategory = edocMarkCategory;
    }

    public String getWordNo() {
        return this.wordNo;
    }
    
    public void setWordNo(String wordNo) {
        this.wordNo = wordNo;
    }

//    public boolean isYearEnabled()
//    {
//    	return yearEnabled;
//    }
//    
//    public void setYearEnabled(boolean b)
//    {
//    	this.yearEnabled = b;
//    }
    
    public String getExpression() {
        return this.expression;
    }
    
    public void setExpression(String expression) {
        this.expression = expression;
    }

    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }

    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }

    public Long getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }    

    public Set<EdocMarkAcl> getEdocMarkAcls() {
        return this.edocMarkAcls;
    }
    
    public void setEdocMarkAcls(Set<EdocMarkAcl> edocMarkAcls) {
        this.edocMarkAcls = edocMarkAcls;
    }

	public Integer getMarkType() {
		return markType;
	}

	public void setMarkType(Integer markType) {
		this.markType = markType;
	}

	public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	public Integer getSortNo() {
		return sortNo;
	}

	public List<EdocMarkAcl> getMarkAclList() {
		return markAclList;
	}

	public void setMarkAclList(List<EdocMarkAcl> markAclList) {
		this.markAclList = markAclList;
	}

}