package com.seeyon.v3x.edoc.domain;

import java.io.Serializable;
import java.util.Comparator;
import java.util.Date;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * EdocMarks generated by MyEclipse - Hibernate Tools
 */
public class EdocMark extends BaseModel implements Serializable, Comparator<EdocMark> {
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	// Fields    

	private EdocMarkDefinition edocMarkDefinition;
	private Long markDefId = -1L;
	private Long edocId = -1L;
	private String subject;
	private String docMark;
	private Integer docMarkNo;
	private Integer yearNo;
	private Long categoryId;
	private Long createUserId;
	private Date createTime;
	private int status;
	private Integer realUsed = 1;//1真正占用 0做为同流水号被存在(用于同流水号都被占用)
	private Integer isLast = 1;//断号是否为最后使用 1是 0否(用于多个公文使用同一个断号，只显示最后使用的断号)
	private Long domainId;
	private int markNum=1;//1使用元素doc_mark  2使用元素doc_mark2
	private Integer govdocType=0;
	private Integer selectType = 0;//占号类型 0自动 1手写 2断号 3预留 4线下占用
	private Integer markType;//0公文文号 1内部文号 2签收编号
	private String memo;
	public static final int STATUS110 = 110;  
	
	public String getMemo() {
		return memo;
	}
	public void setMemo(String memo) {
		this.memo = memo;
	}
	public void setMarkNum(int markNum)
	{
		this.markNum=markNum;
	}
	public int getMarkNum()
	{
		return this.markNum;
	}

    // Constructor



	/** default constructor */
    public EdocMark() {
    }	
    
    // Property accessors

    public EdocMarkDefinition getEdocMarkDefinition() {
        return this.edocMarkDefinition;
    }
    
    public void setEdocMarkDefinition(EdocMarkDefinition edocMarkDefinition) {
        this.edocMarkDefinition = edocMarkDefinition;
    }

    public Long getEdocId() {
    	if(edocId == null) {
			return -1L;
		}
		return edocId;
    }
    
    public void setEdocId(Long edocId) {
    	if(edocId==null) {
			this.edocId = -1L;
		} else {
			this.edocId = edocId;
		}
    }

    public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getDocMark() {
        return this.docMark;
    }
    
    public void setDocMark(String docMark) {
        this.docMark = docMark;
    }

    public Long getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getDocMarkNo() {
		return docMarkNo;
	}

	public void setDocMarkNo(Integer docMarkNo) {
		this.docMarkNo = docMarkNo;
	}

	public Integer getYearNo() {
		return yearNo;
	}
	public void setYearNo(Integer yearNo) {
		this.yearNo = yearNo;
	}
	public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
	public Long getMarkDefId() {
		if(markDefId == null) {
			return -1L;
		}
		return markDefId;
	}
	public void setMarkDefId(Long markDefId) {
		if(markDefId==null) {
			this.markDefId = -1L;
		} else {
			this.markDefId = markDefId;
		}
	}
	public Integer getRealUsed() {
		return realUsed;
	}
	public void setRealUsed(Integer realUsed) {
		this.realUsed = realUsed;
	}
	public Integer getIsLast() {
		return isLast;
	}
	public void setIsLast(Integer isLast) {
		this.isLast = isLast;
	}
	public Integer getSelectType() {
		return selectType;
	}
	public void setSelectType(Integer selectType) {
		this.selectType = selectType;
	}
	public Integer getMarkType() {
		return markType;
	}
	public void setMarkType(Integer markType) {
		this.markType = markType;
	}
	public void setGovdocType(Integer govdocType) {
		this.govdocType = govdocType;
	}
	public Integer getGovdocType() {
		return govdocType;
	}
	
	@Override
	public int compare(EdocMark o1, EdocMark o2) {
		int res=0;
		Integer d1 = o1.getDocMarkNo();
		Integer d2 = o2.getDocMarkNo();
		if(d1!=null && d2!=null) {
			res = d2.compareTo(d1);
		} else if(d2==null && d1!=null) {
			res=-1;
		} else if(d2!=null && d1==null) {
			res=1;
		}
		return res==0?0:res>0?-1:1;
	}
	
    
}