CREATE TABLE "ORG_MEMBER_263EMAIL_MAPPER" (
"USER_ID" NUMBER NOT NULL primary key,
"LOGIN_NAME" VARCHAR2(255 BYTE) NULL ,
"MAIL_263_NAME" VARCHAR2(255 BYTE) NULL ,
"STATUS" VARCHAR2(255 BYTE) NULL ,
"UPDATE_TIME" VARCHAR2(255 BYTE) NULL ,
"CREATE_TIME" VARCHAR2(255 BYTE) NULL ,
"DEPT_ID" NUMBER NULL ,
"DEPT_NAME" VARCHAR2(255 BYTE) NULL
);

COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."USER_ID" IS '用户id';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."LOGIN_NAME" IS '用户登录名';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."MAIL_263_NAME" IS '263邮箱账户名';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."STATUS" IS '状态值';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."DEPT_ID" IS '所属部门id';
COMMENT ON COLUMN "ORG_MEMBER_263EMAIL_MAPPER"."DEPT_NAME" IS '所属部门名称';


